@startuml kampus


actor mahasiswa as mhs
actor dosen as dosen
actor admin as admin

package kelas{
    usecase "menerima jadwal perkuliahan" as U1
    usecase "mengajar" as U2
    usecase "pilih matkul" as U3
    usecase "manage course" as U4
    usecase "add course" as U5
    usecase "remove course" as U6
    usecase "belajar" as U7
} 


mhs  --> U3
U3 ..> U1 : include
dosen --> U1
admin --> U4
U4 ..> U5 : extend
U4 ..> U6 : extend
U1 --> U7 : mahasiswa
U1 --> U2 : dosen
U5 ..> U3 : include